FROM nginx:alpine
COPY ./index.html /usr/share/nginx/html/index.html

#   docker build -t todo-frontend-lab3 ./frontend
#   docker run -d --name frontend --network todo-net -p 8080:80 todo-frontend
